#!/bin/sh

CDIR=$(pwd)
SOURCEDIR=${CDIR}/source
COMPDIR=${CDIR}/components
LOGDIR=${CDIR}/log
WORKDIR=${CDIR}/work
OS=${CDIR}/OS

ARCH=$(uname -m)
THREADS=$(nproc)

TARGET=${ARCH}-linux-gnu
#TARGET=${ARCH}-linux-gnueabi
#TARGET=${ARCH}-linux-gnueabihf

PATH=${OS}/tools/bin:/bin:/usr/bin:/sbin:/usr/sbin

case $(uname -m) in
  x86_64) SUBARCH="i686" ;;
  aarch64) SUBARCH="arm" ;;
  powerpc64 | ppc64) SUBARCH="powerpc" ;;
  *) SUBARCH="" ;;
esac
