#!/bin/bash
set -e

source config

if [ -z $2 ]; then
	echo "Usage: build [STAGE] [TARGET]"
	exit 1
fi

STAGE=$1
COMP=$2

if [ ! -e ${COMPDIR}/${COMP} ]; then
	echo "component \"${COMP}\" not found"
	exit 1
fi

scripts/download ${COMP}
scripts/extract ${COMP}

unset name version source sha1sum folder
source ${COMPDIR}/${COMP}/info

if [ -z ${folder} ]; then
	folder=${name}-${version}
fi

cd ${WORKDIR}/${name}-${version}/${folder}
unset _configure _build _install
source ${COMPDIR}/${COMP}/${STAGE}

if [ -e ${LOGDIR}/${STAGE}/${COMP} ]; then
	rm -rf ${LOGDIR}/${STAGE}/${COMP}
fi
mkdir -p ${LOGDIR}/${STAGE}/${COMP}

if [ -e ${COMPDIR}/${COMP}/patch ]; then
	for f in ${COMPDIR}/${COMP}/patch/*.patch; do
		patch -Np1 -i $f &> ${LOGDIR}/${STAGE}/${COMP}/patch.log || exit 1
		echo "[${COMP}] patching with ${f##*/}"
	done
fi

if [ ! -z $(type -t _configure) ]; then
	echo "[${COMP}] configuring"
	_configure &> ${LOGDIR}/${STAGE}/${COMP}/configure.log || exit 1
fi

if [ ! -z $(type -t _build) ]; then
	echo "[${COMP}] building"
	_build &> ${LOGDIR}/${STAGE}/${COMP}/build.log || exit 1
fi

if [ ! -z $(type -t _install) ]; then
	echo "[${COMP}] installing"
	_install &> ${LOGDIR}/${STAGE}/${COMP}/install.log || exit 1
fi

cd ${CDIR}

if [ -z ${noclean} ]; then
	echo "[${COMP}] cleaning"
	rm -rf ${WORKDIR}/${name}-${version}
fi

echo "[${COMP}] complete"
