#!/bin/bash
set -e

source config

if [ -z $2 ]; then
	echo "Usage: build [STAGE] [TARGET] (clean)"
	exit 1
fi

STAGE=$1
COMP=$2

if [ ! -e ${COMPDIR}/${COMP} ]; then
	echo "component \"${COMP}\" not found"
	exit 1
fi

unset name version source sha1sum folder
source ${COMPDIR}/${COMP}/info
date +"%Y-%m-%d %H:%m:%S.%N" > .start

if [ -z ${folder} ]; then
	PROTOCOL=$(echo ${source} | cut -d ":" -f 1)
	if [ "${PROTOCOL}" == "git" ]; then
		folder=${name}
	else
		folder=${name}-${version}
	fi
fi

if [ "$3" == "clean" ] && [ -e ${LOGDIR}/${STAGE}/${COMP} ]; then
	echo "[${COMP}] performing clean build"
	rm -rf ${LOGDIR}/${STAGE}/${COMP}
elif [ -e ${LOGDIR}/${STAGE}/${COMP}/.complete ]; then
	echo "[${COMP}] already built"
	exit 0
fi

mkdir -p ${LOGDIR}/${STAGE}/${COMP}

scripts/download ${COMP}

if [ ! -e ${LOGDIR}/${STAGE}/${COMP}/.extract-complete ]; then
	scripts/extract ${COMP}
	touch ${LOGDIR}/${STAGE}/${COMP}/.extract-complete
else
	echo "[${COMP}] already extracted"
fi

CURWORKDIR=${WORKDIR}/${name}-${version}/${folder}

cd ${CURWORKDIR}
unset _configure _build _install
source ${COMPDIR}/${COMP}/${STAGE}

if [ -e ${COMPDIR}/${COMP}/patch ] && [ ! -e ${LOGDIR}/${STAGE}/${COMP}/.patch-complete ]; then
	for f in ${COMPDIR}/${COMP}/patch/*.patch; do
		patch -Np1 -i $f &> ${LOGDIR}/${STAGE}/${COMP}/patch.log || exit 1
		echo "[${COMP}] patching with ${f##*/}"
	done
	touch ${LOGDIR}/${STAGE}/${COMP}/.patch-complete
fi

if [ ! -z $(type -t _configure) ] && [ ! -e ${LOGDIR}/${STAGE}/${COMP}/.configure-complete ]; then
	echo "[${COMP}] configuring"
	_configure &> ${LOGDIR}/${STAGE}/${COMP}/configure.log || exit 1
	touch ${LOGDIR}/${STAGE}/${COMP}/.configure-complete
fi

if [ ! -z $(type -t _build) ] && [ ! -e ${LOGDIR}/${STAGE}/${COMP}/.build-complete ]; then
	echo "[${COMP}] building"
	_build &> ${LOGDIR}/${STAGE}/${COMP}/build.log || exit 1
	touch ${LOGDIR}/${STAGE}/${COMP}/.build-complete
fi

if [ ! -z $(type -t _install) ] && [ ! -e ${LOGDIR}/${STAGE}/${COMP}/.install-complete ]; then
	echo "[${COMP}] installing"
	_install &> ${LOGDIR}/${STAGE}/${COMP}/install.log || exit 1
	touch ${LOGDIR}/${STAGE}/${COMP}/.install-complete
fi

cd ${CDIR}

if [ -z ${noclean} ]; then
	echo "[${COMP}] cleaning"
	rm -rf ${WORKDIR}/${name}-${version}
fi

echo "[${COMP}] complete"
touch ${LOGDIR}/${STAGE}/${COMP}/.complete
date +"%Y-%m-%d %H:%m:%S.%N" > .end
scripts/provides > ${LOGDIR}/${STAGE}/${COMP}/provides 2>/dev/null
