#!/bin/bash
set -e

source config

if [ "$(uname -m)" != "${ARCH}" ]; then
	if [ "${ARCH}" == "${SUBARCH}" ]; then
		LINUX="linux32"
		INTERPRETER=""
		echo "[chroot] \"${SUBARCH}\" subarch of \"$(uname -m)\", using linux32"
	else
		LINUX=""

		case ${ARCH} in
			x86_64) INTERPRETER=qemu-x86_64-static ;;
			i?86) INTERPRETER=qemu-i386-static ;;
			powerpc | ppc) INTERPRETER=qemu-ppc-static ;;
			powerpc64 | ppc64) INTERPRETER=qemu-ppc64-static ;;
			arm*) INTERPRETER=qemu-arm-static ;;
			aarch64) INTERPRETER=qemu-aarch64-static ;;
			*) INTERPRETER=qemu-${ARCH}-static ;;
		esac

		if [ -e /usr/bin/${INTERPRETER} ] && [ ! -e ${OS}/usr/bin/${INTERPRETER} ]; then
			sudo cp /usr/bin/${INTERPRETER} ${OS}/usr/bin/${INTERPRETER}
		elif [ ! -e /usr/bin/${INTERPRETER} ]; then
			echo "[chroot] interpreter \"/usr/bin/${INTERPRETER}\" not found!"
			exit 1
		fi
		echo "[chroot] using interpreter: \"${INTERPRETER}\""
	fi
else
	# Assuming native
	LINUX=""
	INTERPRETER=""
	echo "[chroot] assuming native"
fi


cat << EOF | ${LINUX} chroot ${OS} ${INTERPRETER} bin/bash
cd /usr/src/system; $@
EOF
