#!/bin/bash
set -e

source config

for f in usr/src/system dev/pts dev proc sys run; do
	if mountpoint -q ${OS}/$f; then
		umount -l ${OS}/$f
	fi
done

rm -rf ${WORKDIR} ${LOGDIR} ${OS} ${ARCHIVEDIR} ${INSTALLDIR}

if [ "$1" == "all" ]; then
	rm -rf ${SOURCEDIR}
fi
