#!/bin/bash
set -e

source config

rm -rf ${LOGDIR}
rm -rf ${WORKDIR}

for f in dev/pts dev proc sys run; do
	if mountpoint -q ${OS}/$f; then
		sudo umount -l ${OS}/$f
	fi
done

sudo rm -rf ${OS}

if [ "$1" == "all" ]; then
	rm -rf ${SOURCEDIR}
fi
