#!/bin/bash
set -e

source config

for f in usr/src/system/log dev/pts dev proc sys run; do
	if mountpoint -q ${OS}/$f; then
		sudo umount -l ${OS}/$f
	fi
done

rm -rf ${WORKDIR}

sudo rm -rf ${LOGDIR}
sudo rm -rf ${OS}

if [ "$1" == "all" ]; then
	rm -rf ${SOURCEDIR}
fi
