#!/bin/bash
set -e

source config

echo "[compress] compressing rootfs..."

for f in usr/src/system dev/pts dev proc sys run; do
	if mountpoint -q ${OS}/$f; then
		sudo umount -l ${OS}/$f
	fi
done

sudo cp -rp ${OS} ${OS}-copy
cd ${OS}-copy

tar --acls --xattrs -cpf - . | XZ_OPT="--threads=${THREADS}" xz -z - > ../rootfs_${TARGET}-${OS_RELEASE}.tar.xz

cd ${CDIR}
sudo rm -rf ${OS}-copy

echo "[compress] finished! created rootfs_${TARGET}-${OS_RELEASE}.tar.xz"
