#!/bin/bash
set -e

source config

for f in usr/src/system dev/pts dev proc sys run; do
	if mountpoint -q ${OS}/$f; then
		sudo umount -l ${OS}/$f
	fi
done

sudo cp -r ${OS} ${OS}-copy

cd ${OS}-copy
sudo XZ_OPT="--threads=${THREADS}" tar cfJ ../rootfs_${TARGET}-${OS_RELEASE}.tar.xz *
cd ${CDIR}

sudo rm -rf ${OS}-copy
