#!/bin/bash
set -e

source config

scripts/download mpc
scripts/download mpfr
scripts/download gmp

COMPONENTS="binutils gcc linux-headers glibc libstdc++"

for f in ${COMPONENTS}; do
	scripts/build cross-compiler $f
done
