#!/bin/bash
set -e

source config

COMPONENTS="m4 ncurses bash coreutils diffutils file findutils gawk grep gzip make patch sed tar xz binutils gcc"

for f in ${COMPONENTS}; do
	scripts/build cross-system $f || exit 1
done
