#!/bin/bash
set -e

source config

if [ -z $1 ]; then
	echo "Usage: download [TARGET]"
	exit 1
fi

#COMP=$@

if [ ! -e ${SOURCEDIR} ]; then
	mkdir ${SOURCEDIR}
fi

for COMP in $@; do
	unset name version source sha1sum folder
	source ${COMPDIR}/${COMP}/info

	filename=${source##*/}

	if [ -e ${SOURCEDIR}/${filename} ]; then
		check_sha1sum=$(sha1sum ${SOURCEDIR}/${filename} | cut -d " " -f 1)
		if [ "${check_sha1sum}" != "${sha1sum}" ]; then
			echo "[${COMP}] sha1sum mismatch, re-downloading"
			echo "[${COMP}] ${check_sha1sum} != ${sha1sum}"
			rm ${SOURCEDIR}/${filename}
		fi
	fi

	if [ ! -e ${SOURCEDIR}/${filename} ]; then
		echo "[${COMP}] downloading source"
		wget -q -P ${SOURCEDIR} ${source}
	else
		echo "[${COMP}] source exists, skipping download"
	fi

	check_sha1sum=$(sha1sum ${SOURCEDIR}/${filename} | cut -d " " -f 1)
	if [ "${check_sha1sum}" != "${sha1sum}" ]; then
		echo "[${COMP}] sha1sum mismatch, removing"
		echo "[${COMP}] ${check_sha1sum} != ${sha1sum}"
		rm ${SOURCEDIR}/${filename}
		exit 1
	fi
done
