#!/bin/bash
set -e

source config

if [ -z $1 ]; then
	echo "Usage: extract [TARGET]"
	exit 1
fi

COMP=$1

mkdir -p ${WORKDIR}

unset name version source sha1sum folder
source ${COMPDIR}/${COMP}/info
filename=${source##*/}

if [ ! -e ${SOURCEDIR}/${filename} ]; then
	echo "[${COMP}] source doesn't exist, exiting"
	exit 1
fi

PROTOCOL=$(echo ${source} | cut -d ":" -f 1)
case ${PROTOCOL} in
	http|https|ftp)

		fext=${filename#*.}
		ext=${filename##*.}

		if [ $(echo ${fext} | grep tar) ] && [ "${ext}" != "tar" ]; then
			extension="tar.${ext}"
		else
			extension="${ext}"
		fi

		if [ -e ${WORKDIR}/${name}-${version} ]; then
			rm -rf ${WORKDIR}/${name}-${version}
		fi

		mkdir -p ${WORKDIR}/${name}-${version}

		echo "[${COMP}] extracting source"
		# FIXME - add more
		case ${extension} in
			tar.xz)
				tar -C ${WORKDIR}/${name}-${version} -xJf ${SOURCEDIR}/${filename} ;;
			tar.gz | tgz)
				tar -C ${WORKDIR}/${name}-${version} -xzf ${SOURCEDIR}/${filename} ;;
			tar.bz2)
				tar -C ${WORKDIR}/${name}-${version} -xjf ${SOURCEDIR}/${filename} ;;
			tar)
				tar -C ${WORKDIR}/${name}-${version} -xf ${SOURCEDIR}/${filename} ;;
			xz)
				cd ${WORKDIR}/${name}-${version}
				unxz -c ${SOURCEDIR}/${filename} > ${WORKDIR}/${name}-${version}/$(echo ${filename} | sed -e 's/.xz//g')
				cd ${CDIR} ;;
			gz)
				cd ${WORKDIR}/${name}-${version}
				gunzip -c ${SOURCEDIR}/${filename} > ${WORKDIR}/${name}-${version}/$(echo ${filename} | sed -e 's/.gz//g')
				cd ${CDIR} ;;
			bz2)
				cd ${WORKDIR}/${name}-${version}
				bunzip2 -c ${SOURCEDIR}/${filename} > ${WORKDIR}/${name}-${version}/$(echo ${filename} | sed -e 's/.bz2//g')
				cd ${CDIR} ;;
			zip)
				cd ${WORKDIR}/${name}-${version}
				unzip -q ${SOURCEDIR}/${filename}
				cd ${CDIR} ;;
			#7z) ;;
			#rar) ;;
			*)
				echo "[${COMP}] file type \"${extension}\" not supported"
				exit 1 ;;
		esac
		;;
	git)
		echo "[${COMP}] copying source"
		mkdir -p ${WORKDIR}/${name}-${version}
		cp -r ${SOURCEDIR}/${filename} ${WORKDIR}/${name}-${version}/
		;;
esac
