#!/bin/bash
set -e

source config

if [ -z $1 ]; then
	echo "Usage: rootfs [STAGE]"
	exit 1
fi

STAGE=$1

# FIXME - add more
case ${ARCH} in
	x86_64 | aarch64 | powerpc64)
		BITS=64 ;;
	*)
		BITS=32 ;;
esac

case ${STAGE} in
	cross-compiler)
		echo "[rootfs] Creating cross-compiler root filesystem"
		mkdir -p ${OS}/{usr,lib,var,etc,bin,sbin}
		mkdir -p ${OS}/usr/{lib,sbin}
		if [ "${BITS}" == "64" ]; then
			ln -s lib ${OS}/lib64
			ln -s lib ${OS}/usr/lib64
		fi
		mkdir -p ${OS}/tools ;;
	system)

		if [ ! -e /THIS_IS_A_CHROOT ]; then
			echo "[rootfs] MUST BE RUN IN CHROOT!, exiting"
			exit 1
		else
			rm /THIS_IS_A_CHROOT
		fi

		mkdir -p /{bin,boot,etc/{opt,sysconfig},home,lib/firmware,mnt,opt}
		mkdir -p /{media/{floppy,cdrom},srv,var}
		mkdir -p /usr/{,local/}{bin,include,lib,sbin,src}
		mkdir -p /usr/{,local/}share/{color,dict,doc,info,locale,man}
		mkdir -p /usr/{,local/}share/{misc,terminfo,zoneinfo}
		mkdir -p /usr/{,local/}share/man/man{1..8}
		install -d -m 1777 /tmp /var/tmp
		install -d -m 0750 /root

		mkdir /var/{log,mail,spool}
		ln -s /run /var/run
		ln -s /run/lock /var/lock
		mkdir -p /var/{opt,cache,lib/{color,misc,locate},local}

		ln -s /proc/self/mounts /etc/mtab

		cp -r files/* /

		touch /var/log/{btmp,lastlog,faillog,wtmp}
		chgrp utmp /var/log/lastlog
		chmod 664  /var/log/lastlog
		chmod 600  /var/log/btmp

	;;
	*)
		echo "[rootfs] no such stage \"${STAGE}\""
		exit 1 ;;
esac
