#!/bin/bash
set -e

if [ ! -e /THIS_IS_A_CHROOT ]; then
	echo "[system-cleanup] MUST BE RUN IN CHROOT!, exiting"
	exit 1
else
	rm /THIS_IS_A_CHROOT
fi

source config

if [ -e /usr/bin/qemu-*-static ]; then
	rm /usr/bin/qemu-*-static
fi

# FIXME - add more?
#save_lib="ld-2.31.so libc-2.31.so libpthread-2.31.so libthread_db-1.0.so"

#cd /lib

#for LIB in $save_lib; do
#	if [ -e $LIB ]; then
#		objcopy --only-keep-debug $LIB $LIB.dbg
#		strip --strip-unneeded $LIB
#		objcopy --add-gnu-debuglink=$LIB.dbg $LIB
#	fi
#done

#save_usrlib="libquadmath.so.0.0.0 libstdc++.so.6.0.28
#             libitm.so.1.0.0 libatomic.so.1.2.0"

#cd /usr/lib

#for LIB in $save_usrlib; do
#	if [ -e $LIB ]; then
#		objcopy --only-keep-debug $LIB $LIB.dbg
#		strip --strip-unneeded $LIB
#		objcopy --add-gnu-debuglink=$LIB.dbg $LIB
#	fi
#done

#unset LIB save_lib save_usrlib

find /usr/lib -type f -name \*.a \
   -exec strip --strip-debug {} ';'

find /lib /usr/lib -type f -name \*.so* ! -name \*dbg \
   -exec strip --strip-unneeded {} ';'

find /{bin,sbin} /usr/{bin,sbin,libexec} -type f \
    -exec strip --strip-all {} ';'

rm -rf /tmp/*

rm -f /usr/lib/lib{bfd,opcodes}.a
rm -f /usr/lib/libctf{,-nobfd}.a
rm -f /usr/lib/libbz2.a
rm -f /usr/lib/lib{com_err,e2p,ext2fs,ss}.a
rm -f /usr/lib/libltdl.a
rm -f /usr/lib/libfl.a
rm -f /usr/lib/libz.a

find /usr/lib /usr/libexec -name \*.la -delete

rm -rf /tools
