#!/bin/bash
set -e

source config

COMPONENTS="man-pages tcl expect dejagnu iana-etc glibc tzdata zlib bzip2 xz zstd file readline m4 bc flex binutils gmp mpfr mpc attr acl libcap shadow gcc pkg-config ncurses sed psmisc gettext bison grep dash bash libtool gdbm gperf expat inetutils perl xml-parser intltool autoconf automake kmod elfutils libffi openssl python coreutils check diffutils gawk findutils groff less gzip iproute2 kbd libpipeline make patch man-db tar texinfo vim eudev udev-lfs procps-ng util-linux e2fsprogs sysklogd sysvinit libtasn1 p11-kit make-ca wget lfs-bootscripts cpio libxml2 docbook-xsl unzip sgml-common docbook libxslt asciidoc dracut dhcp dhcpcd blfs-bootscripts sudo curl openssh git linux"

case ${ARCH} in
	x86_64) COMPONENTS+=" efivar popt unifont efibootmgr grub grub-efi" ;;
	*) COMPONENTS+=" grub" ;;
esac

for f in ${COMPONENTS}; do
	scripts/build system $f || exit 1
done
